version: "3.9"

services:
  node:
    image: node:16
    container_name: justissimo_backend_node
    volumes:
      - ./:/app
    ports:
      - 3333:3333
    depends_on:
      - db
    working_dir: /app
    command: yarn dev
  db:
    image: postgres:14.1-alpine
    container_name: justissimo_backend_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - TZ=America/Sao_Paulo
    volumes:
      - ./prisma/database/pgsql_data:/var/lib/postgresql/data
networks:
  default:
    external:
      name: justissimo_network